#!/bin/bash

. ~/bin/keymap

COMMAND=$(build_remap_keys_command F9:RIGHT_ARROW F8:UP_ARROW F7:DOWN_ARROW F6:LEFT_ARROW RIGHT_ARROW:RIGHT_CONTROL UP_ARROW:RIGHT_CONTROL LEFT_ARROW:RIGHT_CONTROL DOWN_ARROW:RIGHT_CONTROL)

echo $COMMAND | bash
